// ============================================
// SMARTDEBATE - DATABASE FILE
// src/database/debateData.js
// ============================================

export let debatesArray = [
  {
    id: 1,
    title: "Is AI a Threat to Humanity?",
    topic: "Technology",
    author: "Ahmed Khan",
    description: "Should we be concerned about artificial intelligence advancement and its impact on society?",
    status: "Active",
    date: "2026-03-15",
    participants: 24,
    rating: 4.8,
    votes: 156,
    difficulty: "Advanced",
    trending: true,
    views: 2845,
    category: "Tech & Innovation",
  },
  {
    id: 2,
    title: "Climate Change Solutions",
    topic: "Climate",
    author: "Fatima Ali",
    description: "What are the most effective solutions to combat climate change globally?",
    status: "Active",
    date: "2026-03-12",
    participants: 18,
    rating: 4.6,
    votes: 143,
    difficulty: "Intermediate",
    trending: true,
    views: 1950,
    category: "Environment",
  },
  {
    id: 3,
    title: "Messi vs Ronaldo",
    topic: "Sports",
    author: "Hassan Malik",
    description: "Who is the greatest football player of all time?",
    status: "Closed",
    date: "2026-03-10",
    participants: 32,
    rating: 4.9,
    votes: 287,
    difficulty: "Beginner",
    trending: false,
    views: 5620,
    category: "Sports",
  },
  {
    id: 4,
    title: "Future of Education",
    topic: "Education",
    author: "Zara Khan",
    description: "Should online education completely replace traditional classroom schooling?",
    status: "Active",
    date: "2026-03-18",
    participants: 15,
    rating: 4.5,
    votes: 98,
    difficulty: "Intermediate",
    trending: false,
    views: 1203,
    category: "Learning",
  },
  {
    id: 5,
    title: "Pakistan's Economic Future",
    topic: "Politics",
    author: "Ali Raza",
    description: "What economic policies will help improve Pakistan's financial stability?",
    status: "Active",
    date: "2026-03-16",
    participants: 22,
    rating: 4.7,
    votes: 167,
    difficulty: "Advanced",
    trending: true,
    views: 3421,
    category: "Politics",
  },
  {
    id: 6,
    title: "Cryptocurrency Future",
    topic: "Technology",
    author: "Sara Ahmed",
    description: "Will cryptocurrency replace traditional banking systems in the future?",
    status: "Active",
    date: "2026-03-19",
    participants: 31,
    rating: 4.4,
    votes: 201,
    difficulty: "Advanced",
    trending: true,
    views: 4156,
    category: "Finance",
  },
  {
    id: 7,
    title: "Social Media: Good or Bad?",
    topic: "Technology",
    author: "Nida Malik",
    description: "Is social media doing more harm than good to the younger generation?",
    status: "Active",
    date: "2026-03-20",
    participants: 19,
    rating: 4.3,
    votes: 120,
    difficulty: "Beginner",
    trending: false,
    views: 980,
    category: "Tech & Innovation",
  },
  {
    id: 8,
    title: "Online vs Traditional Learning",
    topic: "Education",
    author: "Usman Tariq",
    description: "Which mode of learning is more effective for students in today's world?",
    status: "Active",
    date: "2026-03-21",
    participants: 27,
    rating: 4.6,
    votes: 175,
    difficulty: "Intermediate",
    trending: true,
    views: 2100,
    category: "Learning",
  },
];

export let nextId = 9;
